yandex-cloud/examples

jenkins-packer/Jenkinsfile, jenkins-packer/packer/base.json, jenkins-packer/packer/django.json, jenkins-packer/packer/nginx.json
Updated Debian 9 to Debian 10 in all Packer configs.
=> Update Debian in the Jenkins/Packer example

serverless/functions/alice/nodejs/parrot/index.js
=> Create example for Alice

serverless/functions/alice/python/parrot/parrot.py
=> Create examples for Alice

datasphere/speech-recognition.ipynb
Из ноутбука удалены логи его выполнения и блок работы с zip, для блока с обучением моделей добавлена строка повышения класса хоста до M.
=> Small fixes in datasphere/speech-recognition

products-prepare/linux/yc-image-cleanup.sh
Update yc-image-cleanup.sh for linux, add new functionality and distributions
=> Update yc-image-cleanup.sh for linux, add new functionality

yds/examples/README.md, yds/examples/putrecord-http-example.py
Python example how to send raw HTTP messages to Yandex Data Streams
=> How to send message to Yandex Data Streams by raw HTTP

tutorials/terraform/README.md, tutorials/terraform/data-from-kafka-to-clickhouse/data-from-kafka-to-clickhouse.tf
* [Task in tracker](https://st.yandex-team.ru/YCDOCIO-1500)
* [Article](https://cloud.yandex.ru/docs/managed-clickhouse/tutorials/fetch-data-from-mkf)
=> YCDOCIO-1500: Add Terraform configuration files for getting data from MKF to MCH

tutorials/terraform/data-transfer/data-transfer-mmy-mysql.tf
@redalka-cloud , привет!
Создали конфигурационный файл для миграции из Облака в пользовательский MySQL.
=> YCDOCIO-1673: added TF manifest for Data-Transfer from MMY to MySQL

tutorials/terraform/data-proc-nat.tf
Привет, @redalka-cloud !
Прошу провести ревью.
[YCDOCIO-1595](https://st.yandex-team.ru/YCDOCIO-1595)
=> YCDOCIO-1595: Terraform configs for Data Proc with NAT instance

tutorials/terraform/kafka-connectors/kafka-mirrormaker-connector.tf
Привет, @redalka-cloud !
Прошу провести ревью конфигурационного файла, необходимого для прохождения руководства по миграции с MirrorMaker 2.
=> YCDOCIO-1659: Terraform config for Kafka Connectors tutorial

tutorials/terraform/logical-replica-amazon-rds-to-postgresql.tf
@redalka-cloud , привет!
Прошу провести ревью в рамках [YCDOCIO-1727](https://st.yandex-team.ru/YCDOCIO-1727).
=> Terraform configuration file for Amazon RDS migration tutorial

tutorials/terraform/data-proc-data-exchange-with-mch.tf
@redalka-cloud , привет! Прошу провести ревью.
[YCDOCIO-1597](https://st.yandex-team.ru/YCDOCIO-1597)
=> YCDOCIO-1597: Terraform configuration for Data Proc tutorial

tutorials/terraform/mes-migration.tf
@redalka-cloud , привет! Прошу провести ревью в рамках задачи [YCDOCIO-1340](https://st.yandex-team.ru/YCDOCIO-1340).
=> YCDOCIO-1340: MES TF Snapshots

tutorials/terraform/data-migration-pgsql-mpg/data-migration-pgsql-mpg.tf, tutorials/terraform/data-migration-pgsql-mpg/data-restore-pgsql-mpg.tf, tutorials/terraform/data-migration-pgsql-mpg/data-transfer-pgsql-mpg.tf
Алла, прошу провести ревью.
Тикет: https://st.yandex-team.ru/YCDOCIO-1744
=> YCDOCIO-1744: Add Terraform to PostgreSQL migration

tutorials/terraform/redis-migration/redis-cluster-non-sharded.tf, tutorials/terraform/redis-migration/redis-cluster-sharded.tf
Алла, привет!
Прошу провести ревью. Тикет [YCDOCIO-1593](https://st.yandex-team.ru/YCDOCIO-1593).
=> YCDOCIO-1593: MRD data migration update

tutorials/terraform/data-transfer/greenplum-clickhouse/greenplum-clickhouse.tf
https://st.yandex-team.ru/YCDOCIO-2017
=> YCDOCIO-2017: DT MGP - MCH

tutorials/terraform/data-transfer/data-transfer-mmy-objs.tf
https://st.yandex-team.ru/YCDOCIO-2128
=> YCDOCIO-2128: MMY OBJS Migration

tutorials/terraform/data-transfer/data-transfer-mkf-ydb.tf
https://st.yandex-team.ru/YCDOCIO-2135
=> YCDOCIO-2135: MKF YDB Migration

tutorials/terraform/data-transfer/greenplum-postgresql.tf
https://st.yandex-team.ru/YCDOCIO-2173
=> YCDOCIO-2173: MGP to MPG

tutorials/terraform/data-transfer/data-transfer-yds-mch.tf
https://st.yandex-team.ru/YCDOCIO-2105
=> YCDOCIO-2105: TF configuration for YDS to MCH transfer

tutorials/terraform/managed-kubernetes/k8s-argocd.tf
Прошу провести ревью манифеста.
Тикет https://st.yandex-team.ru/YCDOCIO-1751
=> YCDOCIO-1751: added TF for mk8s + mgl + registry scenario

tutorials/terraform/data-migration-pgsql-mpg/data-migration-pgsql-mpg.tf, tutorials/terraform/data-migration-pgsql-mpg/data-restore-pgsql-mpg.tf, tutorials/terraform/data-migration-pgsql-mpg/data-transfer-pgsql-mpg.tf
PR для исправления ситуации с отсутствующими файлами в master.
Задача https://st.yandex-team.ru/YCDOCIO-2186
=> Terraform configurations for PG to MPG migration (corrected)

tutorials/terraform/data-transfer/data-transfer-yds-obj.tf
https://st.yandex-team.ru/YCDOCIO-2104
=> YCDOCIO-2104: Add YDS to OBJ Storage migration

tutorials/terraform/data-transfer/postgresql-to-objstorage.tf
https://st.yandex-team.ru/YCDOCIO-2188
=> YCDOCIO-2188: MPG S3 transfer

tutorials/terraform/managed-kubernetes/k8s-calico.tf
Прошу провести ревью манифеста, тикет https://st.yandex-team.ru/YCDOCIO-1733.
=> YCDOCIO-1733: Add TF to k8s Calico scenario

tutorials/terraform/data-transfer/data-transfer-mkf-mkf.tf
https://st.yandex-team.ru/YCDOCIO-2132
=> YCDOCIO-2132: Data transfer Mkf Mkf

tutorials/terraform/data-transfer/data-transfer-mpg-ydb.tf
https://st.yandex-team.ru/YCDOCIO-2187
=> YCDOCIO-2187 MPG YDB transfer

tutorials/terraform/data-proc-nat-gateway.tf
https://st.yandex-team.ru/YCDOCIO-2237
=> YCDOCIO-2237: Revise TF for DataProc and NAT gateway

tutorials/terraform/k8s-node-local-dns.tf, tutorials/terraform/managed-kubernetes/k8s-node-local-dns.tf
Даша, привет!
Прошу провести ревью PR. Задачи:
https://st.yandex-team.ru/YCDOCIO-1730 (добавление TF)
https://st.yandex-team.ru/YCDOCIO-1587 (доработка сценария)
=> YCDOCIO-1730 and 1587: Add TF to Node Local DNS Scenario

tutorials/terraform/data-transfer/postgresql-to-clickhouse.tf
Прошу провести ревью. 
https://st.yandex-team.ru/YCDOCIO-2154
=> YCDOCIO-2154: Add TF for PG to CH transfer

tutorials/terraform/data-transfer/postgresql-yds.tf
Add MPG-YDS terraform file
https://st.yandex-team.ru/YCDOCIO-2493
=> Feature/YCDOCIO-2493: MPG YDS Datatransfer

tutorials/terraform/managed-kubernetes/k8s-gl.tf
Прошу провести ревью, тикет https://st.yandex-team.ru/YCDOCIO-1163.
=> YCDOCIO-1163: Add TF to k8s GitLab tutorial

tutorials/terraform/data-transfer/data-transfer-ydb-mkf.tf
https://st.yandex-team.ru/YCDOCIO-2491
=> YCDOCIO-2491: Terraform configuration for YDB to MKF transfer

tutorials/terraform/data-transfer/mysql-yds.tf
https://st.yandex-team.ru/YCDOCIO-2495
=> Feature/YCDOCIO-2495: MMY YDS Datatransfer

tutorials/terraform/kafka-greenplum.tf
https://st.yandex-team.ru/YCDOCIO-2134
=> YCDOCIO-2134: MKF MGP Data Transfer

tutorials/terraform/data-transfer/data-transfer-mkf-mes.tf
add terraform file for mkf-mes-data-transfer
https://st.yandex-team.ru/YCDOCIO-2561
=> [REVIEW] YCDOCIO-2561: add terraform file for mkf-mes-data-transfer

tutorials/terraform/data-transfer/data-transfer-mkf-mmg.tf
add mkf-mmg-data-transfer terraform file
https://st.yandex-team.ru/YCDOCIO-2562
=> [REVIEW] YCDOCIO-2562: add mkf-mmg-data-transfer terraform file

tutorials/terraform/data-transfer/data-transfer-mkf-mmy.tf
add terraform file for mkf-mmy-data-transfer tutorial
https://st.yandex-team.ru/YCDOCIO-2563
=> [WIP] YCDOCIO-2563: add terraform file for mkf-mmy-data-transfer tutorial

tutorials/terraform/data-transfer/data-transfer-mkf-mos.tf
add mkf-mos-data-transfer terraform file
https://st.yandex-team.ru/YCDOCIO-2564
=> [REVIEW] YCDOCIO-2564: add mkf-mos-data-transfer terraform file

tutorials/terraform/dataproc-to-dataproc.tf
https://st.yandex-team.ru/YCDOCIO-2246
=> YCDOCIO-2246: Add dataproc-to-dataproc TF

tutorials/terraform/data-proc-data-exchange-with-mch.tf
Remake DataProc to CH tutorial
=> [REVIEW] YCDOCIO-2543: Remake DataProc to CH tutorial

tutorials/terraform/data-transfer/data-transfer-mkf-mos.tf
=> [WIP] YCDOCIO-2564: fix

tutorials/terraform/data-transfer/postgresql-yds.tf
fix tf file for mpg-yds data transfer
=> [REVIEW] YCDOCIO-2708: fix tf file for mpg-yds data transfer

tutorials/terraform/data-transfer/mysql-yds.tf
fix tf file for mmy-yds data transfer
=> [REVIEW] YCDOCIO-2709: fix tf file for mmy-yds data transfer

products-prepare/linux/yc-image-cleanup.sh
=> add support for ALT Workstation

tutorials/terraform/data-from-kafka-to-clickhouse/data-from-kafka-to-clickhouse.tf
Edit Kafka-ClickHouse manifest
=> [REVIEW] YCDOCIO-2736: Edit Kafka-ClickHouse manifest

tutorials/terraform/managed-kubernetes/velero-backup.tf
https://st.yandex-team.ru/YCDOCIO-2198
=> YCDOCIO-2198: K8S Velero backup

tutorials/terraform/data-transfer/data-transfer-ydb-yds.tf
add tf file for ydb yds migration with data transfer
=> [WIP] YCDOCIO-2492: add tf file for ydb yds migration with data transfer

tutorials/terraform/data-transfer/data-transfer-ch-mch.tf
https://st.yandex-team.ru/YCDOCIO-2876
=> [WIP] YCDOCIO-2876: added all the required rules for incoming traffic for ClickHouse

tutorials/terraform/managed-kubernetes/k8s-and-registry-for-alb.tf
https://st.yandex-team.ru/YCDOCIO-2961
add tf file for log-options-alb-ingress in k8s
=> [WIP] YCDOCIO-2961: add tf file for log-options-alb-ingress in k8s

products-prepare/linux/yc-image-cleanup.sh
=> Update yc-image-cleanup.sh script

tutorials/terraform/managed-kubernetes/k8s-and-registry-for-gitlab.tf
tf files for https://st.yandex-team.ru/YCDOCIO-2163
=> [WIP] YCDOCIO-2163: update tf files for k8s

tutorials/terraform/dataproc-to-dataproc.tf
https://st.yandex-team.ru/YCDOCIO-3014
=> [REVIEW] YCDOCIO-3014: Component HIVE deleted from Data Proc docs

tutorials/terraform/data-transfer/mysql-postgresql.tf, tutorials/terraform/data-transfer/postgresql-mysql.tf
MMY-MPG, MPG-MMY transfer manifests
=> [REVIEW] YCDOCIO-2923: MMY-MPG, MPG-MMY transfer manifests

tutorials/terraform/managed-kubernetes/k8s-argocd.tf
https://st.yandex-team.ru/YCDOCIO-2383
fix tf file for argo-cd tutorial in k8s
=> [WIP] YCDOCIO-2383: fix tf file

tutorials/terraform/managed-kubernetes/k8s-and-registry-for-gitlab.tf
https://st.yandex-team.ru/YCDOCIO-2823
add default security group for gitlab
=> [REVIEW] YCDOCIO-2823: add default security group for gitlab

tutorials/terraform/managed-kubernetes/k8s-cluster-with-log-group.tf, tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
https://st.yandex-team.ru/YCDOCIO-2943
add TF files for k8s-fluent-bit-and-master-loggin
=> [WIP] YCDOCIO-2943: add TF files for k8s-fluent-bit-and-master-loggin

products-prepare/linux/yc-image-cleanup.sh
Automated synchronization of yc-image-cleanup changes on 2024-02-21_17-12-36
=> Auto sync yc-image-cleanup 2024-02-21_17-12-36

products-prepare/linux/yc-image-cleanup.sh
Automated synchronization of yc-image-cleanup changes on 2024-02-21_19-40-12
=> Auto sync yc-image-cleanup 2024-02-21_19-40-12

tutorials/terraform/managed-gitlab/container-registry-and-gitlab.tf, tutorials/terraform/managed-kubernetes/k8s-and-registry-for-alb.tf, tutorials/terraform/managed-kubernetes/k8s-and-registry-for-gitlab.tf, tutorials/terraform/managed-kubernetes/k8s-argocd.tf, tutorials/terraform/managed-kubernetes/k8s-calico.tf, tutorials/terraform/managed-kubernetes/k8s-cluster-and-lockbox.tf, tutorials/terraform/managed-kubernetes/k8s-cluster-with-log-group.tf, tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf, tutorials/terraform/managed-kubernetes/k8s-cluster.tf, tutorials/terraform/managed-kubernetes/k8s-for-thumbor.tf, tutorials/terraform/managed-kubernetes/k8s-gateway-api.tf, tutorials/terraform/managed-kubernetes/k8s-gl.tf, tutorials/terraform/managed-kubernetes/k8s-node-local-dns.tf, tutorials/terraform/managed-kubernetes/k8s-validate-cr-image.tf, tutorials/terraform/managed-kubernetes/managed-kubernetes/k8s-yc-logging.tf, tutorials/terraform/managed-kubernetes/velero-backup.tf
https://st.yandex-team.ru/YCDOCIO-3374
=> [Review] YCDOCIO-3374: zonal and regional master -> master_location

tutorials/terraform/managed-kubernetes/k8s-load-balancer.tf
Terraform config for LoadBalancer instruction
=> [WIP] YCDOCIO-3320 Terraform config for LoadBalancer instruction

tutorials/terraform/data-proc-nat-gateway.tf
Corrected Data Proc security group rules
=> [WIP] YCDOCIO-3354 Corrected dataproc security group rules

products-prepare/linux/yc-image-cleanup.sh
Automated synchronization of yc-image-cleanup changes on 2024-05-15_10-16-07
=> Auto sync yc-image-cleanup 2024-05-15_10-16-07

tutorials/terraform/sqoop/clusters-mysql-data-proc-and-vm.tf, tutorials/terraform/sqoop/clusters-postgresql-data-proc-and-vm.tf
https://st.yandex-team.ru/YCDOCIO-3558
Updated Terraform manifests.
=> YCDOCIO-3558: Updated Terraform manifests

products-prepare/linux/yc-image-cleanup.sh
Automated synchronization of yc-image-cleanup changes on 2025-01-15_07-53-15
=> Auto sync yc-image-cleanup 2025-01-15_07-53-15

products-prepare/linux/yc-image-cleanup.sh
Automated synchronization of yc-image-cleanup changes on 2025-01-16_14-44-37
=> Auto sync yc-image-cleanup 2025-01-16_14-44-37
